Store scancode scans locally
nexB/purldb pull request #235
Opened 2023-12-13 06:46 UTC by TG1999

2023-12-13 09:48 UTC, pombredanne requested changes
Thanks! here is some review.

2024-02-01 00:42 UTC, JonoYang requested changes
@TG1999 Sorry for the delay, I've left some comments

2024-02-01 00:42 UTC, JonoYang commented on clearcode/store_scans.py
> +repo_names = [hex(hash)[2:].zfill(3) for hash in range(4096)]
Can you add a comment about what is going on in this list comprehension? I see that you are creating hex values of integers and then ignoring the 0x prefix, but it is not obvious at first glance.

2024-02-01 00:42 UTC, JonoYang commented on clearcode/store_scans.py
> +    if repo_name not in get_github_repos(user_name="TG1999"):
Update the functions so we can pass in a username as a variable

2024-02-01 00:42 UTC, JonoYang commented on clearcode/store_scans.py
> +    #TODO: document this function in great detail, this is a part of spec
Do this TODO and explain how the purl hash is created

2024-02-01 00:42 UTC, JonoYang commented on clearcode/store_scans.py
>  if __name__ == "__main__":
Create a management command out of this, where we can specify the directory, github org, and count as options

2024-02-01 00:42 UTC, JonoYang commented on clearcode/store_scans.py
> +# def run(directory, repo_url):
Remove this if not needed

2024-02-01 00:42 UTC, JonoYang commented on clearcode/store_scans.py
> +            #TODO: this is a bug, we need to log it
Print an error message here when we encounter this condition, for now.

2024-07-15 08:38 UTC, pombredanne commented
@TG1999 gentle ping.

2024-07-22 16:43 UTC, pombredanne approved these changes
Looking good!
Thanks. Merging

2024-07-22 16:44 UTC, merged