Fixes in Debian Index Visitor function.
nexB/purldb pull request #30
Opened 2023-02-11 08:02 UTC by 35C4n0r

Closes #23
Gzip file content will read as text instead of bytes. String version Will be passed instead of Version Object.
Signed-off-by: Jay <jaykumar20march@gmail.com>

2023-02-13 23:54 UTC, JonoYang requested changes
How did you test this fix? Did you run the visitor to visit the Debian repos to see if the `get_uris` method worked? I would like to try this out.

2023-02-13 23:54 UTC, JonoYang commented on minecode/mappers/debian.py
> +import debutils
debutils is imported but not used?

2023-02-14 02:41 UTC, 35C4n0r commented
> How did you test this fix? Did you run the visitor to visit the Debian repos to see if the `get_uris` method worked? I would like to try this out.

@JonoYang the PR is Incomplete, i should have converted it to draft. I still haven't done anything about the ```.dsc```files.

2023-02-21 07:06 UTC, 35C4n0r commented
Closing This PR, New PR #41 .

2023-02-21 07:06 UTC, closed without merging